# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "$python$directory$git_branch$git_status${custom.jj}$character"
add_newline = false
follow_symlinks = false
palette = 'catppuccin_mocha'

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[➜](bold red)"

[directory]
truncate_to_repo = false
truncation_length = 0
style = 'green'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'lavender'

[git_status]
style = 'red'

[python]
format = '[py\($virtualenv\) ]($style)'
style = 'yellow'

[custom.jj]
description = "jj repo state"
when = "jj workspace root --ignore-working-copy"
format = "[](fg:separator) $output "
command = '''
jj log --revisions @ --color always --no-graph --limit 1 --template '
  separate(" ",
    bookmarks,
    if(empty, "", raw_escape_sequence("\x1b[1;31m") ++ "(±)"),
  )
'
'''

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
