#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "arunjit"
email = "arunjit@ajsd.in"

[ui]
editor = "nvim"
default-command = "log"
pager = ["delta", "--side-by-side"]
diff-formatter = ":git"

[git]
colocate = false

[aliases]
amend = ["squash"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[template-aliases]
'format_short_signature(signature)' = '"<" ++ if(signature.name(), signature.name(), label("text warning", "NO NAME")) ++ ">"'
'format_timestamp(ts)' = 'ts.ago()'

[templates]
op_log_node = 'if(current_operation, "@", "◉")'
log_node = '''
label("node",
  coalesce(
    if(!self, label("elided", "⇋")),
    if(current_working_copy, label("working_copy", "◉")),
    if(conflict, label("conflict", "x")),
    if(immutable, label("immutable", "◆")),
    label("normal", "○")
  )
)
'''
