#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "arunjit"
email = "arunjit@ajsd.in"

[ui]
editor = "nvim"
default-command = "log"
pager = ["delta", "--side-by-side"]
diff-formatter = ":git"

[git]
colocate = false
